baseURL = "https://example.org/"
locale = "de-de"
title = "AustauschKompass CMS Backend"

[privacy]
  [privacy.googleAnalytics]
    respectDoNotTrack = true

[[module.imports]]
  path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[[module.imports]]
  ignoreConfig = true
  path = "github.com/twbs/icons"

[[module.imports.mounts]]
  source = "font"
  target = "assets/scss/bootstrap-icons/font"
  files = [ "! fonts"]

[[module.imports.mounts]]
  source = "font/fonts"
  target = "assets/fonts/bootstrap-icons"

[[module.imports]]
  path = "github.com/hotwired/stimulus"

[[module.imports.mounts]]
  source = "src"
  target = "assets/js/stimulus"

[params]
crm_api_url = "https://api.crm.austauschkompass.de"
mt_url = "https://stats.schueleraustausch.net/"

[params.ak_order_components]
js_url = "https://assets.austauschkompass.de/ak-order-components/1/main.js"

[params.ak_order_components.defaults]
rating_api_url = "https://www.schueleraustausch.de"
crm_api_url = "https://api.crm.austauschkompass.de"
order_api_url = "https://api.orders.austauschkompass.de"
upsell = true
upsell_prechecked = true
